### ISSUE TITLE
MMM-MailMessage not connecting to gmail imap server

### ISSUE THREAD

**Issue by roccodicarlo** [Unclearogre/MMM-MailMessage#2]
It doesn't seem to connect to gmail imap server.  The error is shown below.  I tried with APP based password as well as the normal user password.  Both throw same error below.

[25.01.2024 19:29.48.262] [ERROR] (node:33251) UnhandledPromiseRejectionWarning: Error: Could not open socket: self signed certificate
    at socket.onerror (/home/dicarlro/MagicMirror/modules/MMM-MailMessage/node_modules/emailjs-imap-client/src/emailjs-imap-client-imap.js:157:24)
    at TCPSocket._emit (/home/dicarlro/MagicMirror/modules/MMM-MailMessage/node_modules/emailjs-tcp-socket/src/emailjs-tcp-socket.js:1088:9)
    at TLSSocket.<anonymous> (/home/dicarlro/MagicMirror/modules/MMM-MailMessage/node_modules/emailjs-tcp-socket/src/emailjs-tcp-socket.js:324:26)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

[25.01.2024 19:29.48.263] [ERROR] (node:33251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 17)

**Comment by Dotmatrix812** [comment]
Same problem for me, any suggestions ?


0|MagicMirror  | [2024-04-21 10:22:44.030] [ERROR] (node:12407) UnhandledPromiseRejectionWarning: Error: Could not open socket: self signed certificate
0|MagicMirror  |     at socket.onerror (/home/pi/MagicMirror/modules/MMM-MailMessage/node_modules/emailjs-imap-client/src/emailjs-imap-client-imap.js:157:24)
0|MagicMirror  |     at TCPSocket._emit (/home/pi/MagicMirror/modules/MMM-MailMessage/node_modules/emailjs-tcp-socket/src/emailjs-tcp-socket.js:1088:9)
0|MagicMirror  |     at TLSSocket.<anonymous> (/home/pi/MagicMirror/modules/MMM-MailMessage/node_modules/emailjs-tcp-socket/src/emailjs-tcp-socket.js:324:26)
0|MagicMirror  |     at TLSSocket.emit (node:events:514:28)
0|MagicMirror  |     at emitErrorNT (node:internal/streams/destroy:151:8)
0|MagicMirror  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
0|MagicMirror  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
0|MagicMirror  | (Use `electron --trace-warnings ...` to show where the warning was created) 
0|MagicMirror  | [2024-04-21 10:22:44.032] [ERROR] (node:12407) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by Ryker427** [comment]
I'm seeing the same issues as you two. e-mails-tcp-socket is "deprecated" and seems to be the issue. I'm fairly new to this and think maybe a change to the emailjs would fix the issue or maybe find something to replace the current emailjs-imap-client that is old...

**Comment by oskich** [comment]
I'm having trouble with my own domain's IMAP server, seems to some kind of certificate mismatch?

`[ERROR] (node:517466) UnhandledPromiseRejectionWarning: Error: Could not open socket: Hostname/IP does not match certificate's altnames: Host: mail.<myemailserver>.se. is not in the cert's altnames: DNS:omega.hostup.se, DNS:srv12.hostup.se
    at socket.onerror (/home/pi/MagicMirror/modules/MMM-MailMessage/node_modules/emailjs-imap-client/src/emailjs-imap-client-imap.js:157:24)
    at TCPSocket._emit (/home/pi/MagicMirror/modules/MMM-MailMessage/node_modules/emailjs-tcp-socket/src/emailjs-tcp-socket.js:1088:9)
    at TLSSocket.<anonymous> (/home/pi/MagicMirror/modules/MMM-MailMessage/node_modules/emailjs-tcp-socket/src/emailjs-tcp-socket.js:324:26)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
(Use `electron --trace-warnings ...` to show where the warning was created) 
[2025-11-23 19:05:42.145] [ERROR] (node:517466) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) 
`
